package org.example.tomcat1.controller.command;

public enum CommandName {
	LOGINATION, REGISTRATION, SAVENEWUSER, GOTOINDEXPAGE, GOTOMAINPAGE, 
	LOGOUT, GOTONEWSPAGE, GOTOEDITPAGE, MODIFYNEWS, CHANGELOCAL, 
	DELETENEWS, GOTOREDIRECTPAGE
}
