package org.example.tomcat1.controller.command;

public enum CommandName {	
	LOGIN, SAVEUSER, DELETENEWS, LOGOUT, MODIFYNEWS, CHANGELOCAL, 
	GOTOREGISTRATIONPAGE, GOTOINDEXPAGE, GOTOMAINPAGE, 
	GOTOREDIRECTPAGE, GOTONEWSPAGE, GOTOEDITPAGE	
}
